Repository 2023Summer/mr-playlist-backend, pull requests merged in 2023-08, with the labels that each got.

#26 Refactor: Seperate Artist and Group
  src/main/java/summer/mrplaylist/music/dto/ArtistForm.java
  src/main/java/summer/mrplaylist/music/dto/GroupForm.java
  src/main/java/summer/mrplaylist/music/model/Artist.java
  src/main/java/summer/mrplaylist/music/model/Group.java
  src/main/java/summer/mrplaylist/music/model/MainArtist.java
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/music/model/SoloArtist.java
  src/main/java/summer/mrplaylist/music/repository/ArtistRepository.java
  src/main/java/summer/mrplaylist/music/repository/MainArtistRepository.java
  src/main/java/summer/mrplaylist/music/service/ArtistService.java
  src/main/java/summer/mrplaylist/music/service/MusicService.java
  src/test/java/summer/mrplaylist/music/model/MainSoloArtistTest.java
  src/test/java/summer/mrplaylist/music/model/MusicTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceTest.java
  src/test/java/summer/mrplaylist/music/service/MusicServiceTest.java
Labels: refactor

#24 Feature/#19 feature 회원가입 및 시큐리티 적용
  build.gradle
  src/main/java/summer/mrplaylist/PlaylistApplication.java
  src/main/java/summer/mrplaylist/common/config/db/QueryDslConfig.java
  src/main/java/summer/mrplaylist/common/config/db/RedisConfig.java
  src/main/java/summer/mrplaylist/common/config/jwt/JwtAuthenticationFilter.java
  src/main/java/summer/mrplaylist/common/config/jwt/JwtProperties.java
  src/main/java/summer/mrplaylist/common/config/security/WebSecurityConfig.java
  src/main/java/summer/mrplaylist/common/constant/JwtTokenConstants.java
  src/main/java/summer/mrplaylist/common/dto/.gitkeep
  src/main/java/summer/mrplaylist/common/dto/JwtTokenDto.java
  src/main/java/summer/mrplaylist/common/model/.gitkeep
  src/main/java/summer/mrplaylist/common/model/UserDetailsImpl.java
  src/main/java/summer/mrplaylist/common/service/.gitkeep
  src/main/java/summer/mrplaylist/common/service/JwtTokenProvider.java
  src/main/java/summer/mrplaylist/common/service/RedisService.java
  src/main/java/summer/mrplaylist/common/service/UserDetailsServiceImpl.java
  src/main/java/summer/mrplaylist/member/constant/.gitkeep
  src/main/java/summer/mrplaylist/member/constant/MemberConstants.java
  src/main/java/summer/mrplaylist/member/constant/Role.java
  src/main/java/summer/mrplaylist/member/controller/.gitkeep
  src/main/java/summer/mrplaylist/member/controller/MemberController.java
  src/main/java/summer/mrplaylist/member/dto/.gitkeep
  src/main/java/summer/mrplaylist/member/dto/AddMemberRequestDto.java
  src/main/java/summer/mrplaylist/member/dto/LoginMemberRequestDto.java
  src/main/java/summer/mrplaylist/member/dto/UpdateMemberRequestDto.java
  src/main/java/summer/mrplaylist/member/model/Email.java
  src/main/java/summer/mrplaylist/member/model/Member.java
  src/main/java/summer/mrplaylist/member/repository/.gitkeep
  src/main/java/summer/mrplaylist/member/repository/MemberRepository.java
  src/main/java/summer/mrplaylist/member/service/.gitkeep
  src/main/java/summer/mrplaylist/member/service/EmailService.java
  src/main/java/summer/mrplaylist/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/summer/mrplaylist/common/config/db/RedisConfigTest.java
  src/test/java/summer/mrplaylist/common/config/jwt/JwtTokenProviderTest.java
  src/test/java/summer/mrplaylist/member/service/EmailServiceTest.java
  src/test/resources/application.yml
Labels: feature

#28 Feature/#15 create playlist
  build.gradle
  src/main/java/summer/mrplaylist/member/model/Member.java
  src/main/java/summer/mrplaylist/member/repository/MemberRepository.java
  src/main/java/summer/mrplaylist/music/constant/.gitkeep
  src/main/java/summer/mrplaylist/music/constant/ArtistConstants.java
  src/main/java/summer/mrplaylist/music/dto/.gitkeep
  src/main/java/summer/mrplaylist/music/dto/ArtistForm.java
  src/main/java/summer/mrplaylist/music/dto/GroupForm.java
  src/main/java/summer/mrplaylist/music/dto/MusicForm.java
  src/main/java/summer/mrplaylist/music/model/Artist.java
  src/main/java/summer/mrplaylist/music/model/Group.java
  src/main/java/summer/mrplaylist/music/model/MainArtist.java
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/music/model/SoloArtist.java
  src/main/java/summer/mrplaylist/music/repository/.gitkeep
  src/main/java/summer/mrplaylist/music/repository/MainArtistRepository.java
  src/main/java/summer/mrplaylist/music/repository/MusicRepository.java
  src/main/java/summer/mrplaylist/music/service/.gitkeep
  src/main/java/summer/mrplaylist/music/service/ArtistService.java
  src/main/java/summer/mrplaylist/music/service/MusicService.java
  src/main/java/summer/mrplaylist/playlist/constant/.gitkeep
  src/main/java/summer/mrplaylist/playlist/constant/PlaylistConstant.java
  src/main/java/summer/mrplaylist/playlist/dto/.gitkeep
  src/main/java/summer/mrplaylist/playlist/dto/PlaylistForm.java
  src/main/java/summer/mrplaylist/playlist/model/Category.java
  src/main/java/summer/mrplaylist/playlist/model/Playlist.java
  src/main/java/summer/mrplaylist/playlist/model/PlaylistCategory.java
  src/main/java/summer/mrplaylist/playlist/repository/.gitkeep
  src/main/java/summer/mrplaylist/playlist/repository/CategoryRepository.java
  src/main/java/summer/mrplaylist/playlist/repository/PlaylistCategoryRepository.java
  src/main/java/summer/mrplaylist/playlist/repository/PlaylistRepository.java
  src/main/java/summer/mrplaylist/playlist/service/.gitkeep
  src/main/java/summer/mrplaylist/playlist/service/PlaylistCategoryService.java
  src/main/java/summer/mrplaylist/playlist/service/PlaylistService.java
  src/test/java/summer/mrplaylist/CreateMethod.java
  src/test/java/summer/mrplaylist/music/model/MainSoloArtistTest.java
  src/test/java/summer/mrplaylist/music/model/MusicTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceTest.java
  src/test/java/summer/mrplaylist/music/service/MusicServiceTest.java
  src/test/java/summer/mrplaylist/playlist/service/PlaylistServiceTest.java
Labels: feature

#30 Feat: Add CurrentUser annotation
  src/main/java/summer/mrplaylist/common/config/WebConfig.java
  src/main/java/summer/mrplaylist/common/constant/.gitkeep
  src/main/java/summer/mrplaylist/common/model/UserDetailsImpl.java
  src/main/java/summer/mrplaylist/common/service/JwtTokenProvider.java
  src/main/java/summer/mrplaylist/common/util/.gitkeep
  src/main/java/summer/mrplaylist/common/util/CurrentUser.java
  src/main/java/summer/mrplaylist/common/util/CurrentUserArgumentResolver.java
Labels: feature

#38 Feat: Add Global Response
  src/main/java/summer/mrplaylist/common/dto/PageResponse.java
  src/main/java/summer/mrplaylist/common/dto/Response.java
  src/test/java/summer/mrplaylist/common/dto/ResponseDtoTest.java
Labels: feature

#43 Refactor: Edit duplicate member count
  src/main/java/summer/mrplaylist/common/controller/GlobalControllerAdvice.java
  src/main/java/summer/mrplaylist/common/dto/PageResponse.java
  src/main/java/summer/mrplaylist/common/dto/Response.java
  src/main/java/summer/mrplaylist/music/service/MainArtistService.java
  src/main/java/summer/mrplaylist/music/service/MusicService.java
  src/test/java/summer/mrplaylist/common/dto/ResponseDtoTest.java
  src/test/java/summer/mrplaylist/music/service/MainArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/MainArtistServiceTest.java
  src/test/java/summer/mrplaylist/music/service/MusicServiceTest.java
Labels: refactor

#47 Feat: Add graceful shutdown
  build.gradle
  src/main/java/summer/mrplaylist/common/util/XlsxFileParser.java
  src/main/java/summer/mrplaylist/music/model/SoloArtist.java
  src/main/resources/application.yml
  src/test/java/summer/mrplaylist/common/util/XlsxFileParserTest.java
Labels: feature

#48 Feature/#45 playlist edit delete
  src/main/java/summer/mrplaylist/common/util/XlsxFileParser.java
  src/main/java/summer/mrplaylist/music/constant/ArtistConstants.java
  src/main/java/summer/mrplaylist/music/constant/MusicConstants.java
  src/main/java/summer/mrplaylist/music/dto/ArtistUpdateForm.java
  src/main/java/summer/mrplaylist/music/dto/MusicUpdateForm.java
  src/main/java/summer/mrplaylist/music/model/Group.java
  src/main/java/summer/mrplaylist/music/model/MainArtist.java
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/music/model/SoloArtist.java
  src/main/java/summer/mrplaylist/music/repository/MainArtistRepository.java
  src/main/java/summer/mrplaylist/music/repository/MusicRepository.java
  src/main/java/summer/mrplaylist/music/service/MainArtistService.java
  src/main/java/summer/mrplaylist/music/service/MusicService.java
  src/main/java/summer/mrplaylist/playlist/dto/PlaylistUpdateForm.java
  src/main/java/summer/mrplaylist/playlist/model/Playlist.java
  src/main/java/summer/mrplaylist/playlist/service/PlaylistService.java
  src/main/resources/PlaylistData.xlsx
  src/test/java/summer/mrplaylist/CreateMethod.java
  src/test/java/summer/mrplaylist/music/service/MainArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/playlist/service/PlaylistServiceSpringBootTest.java
  src/test/java/summer/mrplaylist/playlist/service/PlaylistServiceTest.java
  src/test/resources/application.yml
Labels: feature

#58 Feat: Add Rest API
  build.gradle
  src/main/java/summer/mrplaylist/PlaylistApplication.java
  src/main/java/summer/mrplaylist/common/config/JpaAuditingConfiguration.java
  src/main/java/summer/mrplaylist/common/config/jwt/ExceptionHandlerFilter.java
  src/main/java/summer/mrplaylist/common/config/security/WebSecurityConfig.java
  src/main/java/summer/mrplaylist/common/controller/GlobalControllerAdvice.java
  src/main/java/summer/mrplaylist/common/dto/ErrorResponse.java
  src/main/java/summer/mrplaylist/common/dto/PageResponse.java
  src/main/java/summer/mrplaylist/common/dto/Response.java
  src/main/java/summer/mrplaylist/common/service/RedisService.java
  src/main/java/summer/mrplaylist/common/util/XlsxFileParser.java
  src/main/java/summer/mrplaylist/music/controller/.gitkeep
  src/main/java/summer/mrplaylist/music/controller/ArtistController.java
  src/main/java/summer/mrplaylist/music/controller/MusicController.java
  src/main/java/summer/mrplaylist/music/dto/GroupResponse.java
  src/main/java/summer/mrplaylist/music/dto/MusicUpdateForm.java
  src/main/java/summer/mrplaylist/music/dto/SoloArtistResponse.java
  src/main/java/summer/mrplaylist/music/model/MainArtist.java
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/music/service/ArtistService.java
  src/main/java/summer/mrplaylist/music/service/MainArtistService.java
  src/main/java/summer/mrplaylist/music/service/MusicService.java
  src/main/java/summer/mrplaylist/playlist/controller/.gitkeep
  src/main/java/summer/mrplaylist/playlist/controller/PlaylistController.java
  src/main/java/summer/mrplaylist/playlist/dto/PlaylistForm.java
  src/main/java/summer/mrplaylist/playlist/model/Playlist.java
  src/main/java/summer/mrplaylist/playlist/service/PlaylistService.java
  src/main/java/summer/mrplaylist/search/controller/.gitkeep
  src/main/java/summer/mrplaylist/search/controller/SearchController.java
  src/main/java/summer/mrplaylist/search/service/SearchService.java
  src/main/resources/application.yml
  src/test/java/summer/mrplaylist/CreateMethod.java
  src/test/java/summer/mrplaylist/comment/service/CommentServiceTest.java
  src/test/java/summer/mrplaylist/common/dto/ResponseDtoTest.java
  src/test/java/summer/mrplaylist/music/controller/ArtistControllerTest.java
  src/test/java/summer/mrplaylist/music/service/MainArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/MainSoloArtistServiceTest.java
  src/test/java/summer/mrplaylist/playlist/controller/PlaylistControllerTest.java
  src/test/java/summer/mrplaylist/playlist/service/PlaylistServiceSpringBootTest.java
  src/test/java/summer/mrplaylist/playlist/service/PlaylistServiceTest.java
  src/test/java/summer/mrplaylist/search/service/SearchServiceTest.java
Labels: feature, refactor

#60 Feature/#55 feature 좋아요 기능 만들기
  src/main/java/summer/mrplaylist/common/config/db/RedisConfig.java
  src/main/java/summer/mrplaylist/common/config/db/SchedulingConfig.java
  src/main/java/summer/mrplaylist/common/service/JwtTokenProvider.java
  src/main/java/summer/mrplaylist/likes/constant/.gitkeep
  src/main/java/summer/mrplaylist/likes/constant/LikesConstants.java
  src/main/java/summer/mrplaylist/likes/controller/.gitkeep
  src/main/java/summer/mrplaylist/likes/controller/LikesController.java
  src/main/java/summer/mrplaylist/likes/dto/.gitkeep
  src/main/java/summer/mrplaylist/likes/dto/LikesForm.java
  src/main/java/summer/mrplaylist/likes/model/.gitkeep
  src/main/java/summer/mrplaylist/likes/model/Likes.java
  src/main/java/summer/mrplaylist/likes/repository/.gitkeep
  src/main/java/summer/mrplaylist/likes/repository/LikesQRepo.java
  src/main/java/summer/mrplaylist/likes/repository/LikesRepository.java
  src/main/java/summer/mrplaylist/likes/service/.gitkeep
  src/main/java/summer/mrplaylist/likes/service/LikesRedisService.java
  src/main/java/summer/mrplaylist/likes/service/LikesScheduler.java
  src/main/java/summer/mrplaylist/likes/service/LikesService.java
  src/main/java/summer/mrplaylist/member/controller/MemberController.java
  src/main/java/summer/mrplaylist/member/dto/MemberResponse.java
  src/main/java/summer/mrplaylist/member/dto/UpdateMemberRequestDto.java
  src/main/java/summer/mrplaylist/member/service/MemberService.java
  src/main/resources/application.yml
  src/test/java/summer/mrplaylist/CreateMethod.java
  src/test/java/summer/mrplaylist/likes/service/LikesSchedulerTest.java
  src/test/java/summer/mrplaylist/likes/service/LikesServiceTest.java
  src/test/resources/application.yml
Labels: feature
