Repository 2023Summer/mr-playlist-backend, pull requests merged in 2023-07, with the labels that each got.

#4 Test/#3 issue test
  README.md
Labels: help wanted

#6 Test: git연습 원상복구해보기.
  README.md
Labels: help wanted

#8 Feature/#7 db log setting
  build.gradle
  src/main/java/summer/mrplaylist/comment/model/Comment.java
  src/main/java/summer/mrplaylist/common/config/p6spy/P6spyConfig.java
  src/main/java/summer/mrplaylist/common/config/p6spy/P6spyPrettySqlFormatter.java
  src/main/java/summer/mrplaylist/like/service/.gitkeep
  src/main/java/summer/mrplaylist/likes/constant/.gitkeep
  src/main/java/summer/mrplaylist/likes/controller/.gitkeep
  src/main/java/summer/mrplaylist/likes/dto/.gitkeep
  src/main/java/summer/mrplaylist/likes/model/.gitkeep
  src/main/java/summer/mrplaylist/likes/model/Likes.java
  src/main/java/summer/mrplaylist/likes/repository/.gitkeep
  src/main/java/summer/mrplaylist/likes/service/.gitkeep
  src/main/java/summer/mrplaylist/music/model/Artist.java
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/playlist/model/.gitkeep
  src/main/java/summer/mrplaylist/playlist/model/Playlist.java
  src/main/java/summer/mrplaylist/playlist/model/PlaylistCategory.java
  src/main/java/summer/mrplaylist/playlist/model/PlaylistMusic.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/java/summer/mrplaylist/logback/LogbackTest.java
Labels: feature

#12 Banner : 배너 추가하기
  src/main/resources/banner.txt
Labels: feature

#11 Doc: Add pr template
  .github/PULL_REQUEST_TEMPLATE/pr-template.md
Labels: documentation

#14 Feat: Add queryfactory bean
  build.gradle
  src/main/java/summer/mrplaylist/common/config/QueryDslConfig.java
Labels: feature

#17 Reafactor: DB schema change
  src/main/java/summer/mrplaylist/music/model/Music.java
  src/main/java/summer/mrplaylist/playlist/model/Playlist.java
  src/main/java/summer/mrplaylist/playlist/model/PlaylistMusic.java
Labels: refactor

#20 Feat: Add create Artist and Group
  build.gradle
  src/main/java/summer/mrplaylist/music/dto/ArtistForm.java
  src/main/java/summer/mrplaylist/music/dto/GroupForm.java
  src/main/java/summer/mrplaylist/music/model/Artist.java
  src/main/java/summer/mrplaylist/music/repository/ArtistRepository.java
  src/main/java/summer/mrplaylist/music/service/ArtistService.java
  src/test/java/summer/mrplaylist/music/model/ArtistTest.java
  src/test/java/summer/mrplaylist/music/service/ArtistServiceBootTest.java
  src/test/java/summer/mrplaylist/music/service/ArtistServiceTest.java
Labels: feature
